// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: order/v1/messages.proto

package order_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EventOrderCreated with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *EventOrderCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventOrderCreated with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// EventOrderCreatedMultiError, or nil if none found.
func (m *EventOrderCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *EventOrderCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	if len(errors) > 0 {
		return EventOrderCreatedMultiError(errors)
	}

	return nil
}

// EventOrderCreatedMultiError is an error wrapping multiple validation errors
// returned by EventOrderCreated.ValidateAll() if the designated constraints
// aren't met.
type EventOrderCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventOrderCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventOrderCreatedMultiError) AllErrors() []error { return m }

// EventOrderCreatedValidationError is the validation error returned by
// EventOrderCreated.Validate if the designated constraints aren't met.
type EventOrderCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventOrderCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventOrderCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventOrderCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventOrderCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventOrderCreatedValidationError) ErrorName() string {
	return "EventOrderCreatedValidationError"
}

// Error satisfies the builtin error interface
func (e EventOrderCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventOrderCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventOrderCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventOrderCreatedValidationError{}
